### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by oasif** [ngageoint/opensphere-app-example#1]
first error:
ERROR - required "os.mixin.cesium" namespace never provided goog.require('os.mixin.cesium');

then:
{
  "status": 1,
  "file": "/opt/osyw/workspace/opensphere-app-example/.build/combined.scss",
  "line": 11,
  "column": 1,
  "message": "File to import not found or unreadable: ui/partials/flex.\nParent style sheet: /opt/osyw/workspace/opensphere-app-example/.build/combined.scss",
  "formatted": "Error: File to import not found or unreadable: ui/partials/flex.\n       Parent style sheet: /opt/osyw/workspace/opensphere-app-example/.build/combined.scss\n        on line 11 of .build/combined.scss\n>> @import 'ui/partials/flex';\n   ^\n"
}
 and
{
  "status": 1,
  "file": "/opt/osyw/workspace/opensphere-app-example/.build/combined.scss",
  "line": 12,
  "column": 1,
  "message": "File to import not found or unreadable: os/overrides/openlayers.\nParent style sheet: /opt/osyw/workspace/opensphere-app-example/.build/combined.scss",
  "formatted": "Error: File to import not found or unreadable: os/overrides/openlayers.\n       Parent style sheet: /opt/osyw/workspace/opensphere-app-example/.build/combined.scss\n        on line 12 of .build/combined.scss\n>> @import 'os/overrides/openlayers';\n   ^\n"
}

**Comment by schmidtk** [comment]
We made some updates to OpenSphere (moving Cesium to a plugin, upgrading to Bootstrap 4) that weren't updated in this example. I'll have those cleaned up shortly. Thanks!

**Comment by oasif** [comment]
I appreciate the quick fix. Great work!
